//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIESC_ConUni_DotNet_GR6.MiServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiServicio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IService1/CelsiusAFahrenheitResponse")]
        double CelsiusAFahrenheit(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IService1/CelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelsiusAFahrenheitAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitACelsius", ReplyAction="http://tempuri.org/IService1/FahrenheitACelsiusResponse")]
        double FahrenheitACelsius(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitACelsius", ReplyAction="http://tempuri.org/IService1/FahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitACelsiusAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusAKelvin", ReplyAction="http://tempuri.org/IService1/CelsiusAKelvinResponse")]
        double CelsiusAKelvin(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusAKelvin", ReplyAction="http://tempuri.org/IService1/CelsiusAKelvinResponse")]
        System.Threading.Tasks.Task<double> CelsiusAKelvinAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KelvinACelsius", ReplyAction="http://tempuri.org/IService1/KelvinACelsiusResponse")]
        double KelvinACelsius(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KelvinACelsius", ReplyAction="http://tempuri.org/IService1/KelvinACelsiusResponse")]
        System.Threading.Tasks.Task<double> KelvinACelsiusAsync(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitAKelvin", ReplyAction="http://tempuri.org/IService1/FahrenheitAKelvinResponse")]
        double FahrenheitAKelvin(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitAKelvin", ReplyAction="http://tempuri.org/IService1/FahrenheitAKelvinResponse")]
        System.Threading.Tasks.Task<double> FahrenheitAKelvinAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KelvinAFahrenheit", ReplyAction="http://tempuri.org/IService1/KelvinAFahrenheitResponse")]
        double KelvinAFahrenheit(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KelvinAFahrenheit", ReplyAction="http://tempuri.org/IService1/KelvinAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> KelvinAFahrenheitAsync(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KmAMetros", ReplyAction="http://tempuri.org/IService1/KmAMetrosResponse")]
        double KmAMetros(double kilometros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KmAMetros", ReplyAction="http://tempuri.org/IService1/KmAMetrosResponse")]
        System.Threading.Tasks.Task<double> KmAMetrosAsync(double kilometros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MetrosACm", ReplyAction="http://tempuri.org/IService1/MetrosACmResponse")]
        double MetrosACm(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MetrosACm", ReplyAction="http://tempuri.org/IService1/MetrosACmResponse")]
        System.Threading.Tasks.Task<double> MetrosACmAsync(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PulgadasACm", ReplyAction="http://tempuri.org/IService1/PulgadasACmResponse")]
        double PulgadasACm(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PulgadasACm", ReplyAction="http://tempuri.org/IService1/PulgadasACmResponse")]
        System.Threading.Tasks.Task<double> PulgadasACmAsync(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PiesAMetros", ReplyAction="http://tempuri.org/IService1/PiesAMetrosResponse")]
        double PiesAMetros(double pies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PiesAMetros", ReplyAction="http://tempuri.org/IService1/PiesAMetrosResponse")]
        System.Threading.Tasks.Task<double> PiesAMetrosAsync(double pies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MillasAKm", ReplyAction="http://tempuri.org/IService1/MillasAKmResponse")]
        double MillasAKm(double millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MillasAKm", ReplyAction="http://tempuri.org/IService1/MillasAKmResponse")]
        System.Threading.Tasks.Task<double> MillasAKmAsync(double millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KgAGramos", ReplyAction="http://tempuri.org/IService1/KgAGramosResponse")]
        double KgAGramos(double kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KgAGramos", ReplyAction="http://tempuri.org/IService1/KgAGramosResponse")]
        System.Threading.Tasks.Task<double> KgAGramosAsync(double kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GramosAMg", ReplyAction="http://tempuri.org/IService1/GramosAMgResponse")]
        double GramosAMg(double gramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GramosAMg", ReplyAction="http://tempuri.org/IService1/GramosAMgResponse")]
        System.Threading.Tasks.Task<double> GramosAMgAsync(double gramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LibrasAKg", ReplyAction="http://tempuri.org/IService1/LibrasAKgResponse")]
        double LibrasAKg(double libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LibrasAKg", ReplyAction="http://tempuri.org/IService1/LibrasAKgResponse")]
        System.Threading.Tasks.Task<double> LibrasAKgAsync(double libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OnzasAGramos", ReplyAction="http://tempuri.org/IService1/OnzasAGramosResponse")]
        double OnzasAGramos(double onzas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OnzasAGramos", ReplyAction="http://tempuri.org/IService1/OnzasAGramosResponse")]
        System.Threading.Tasks.Task<double> OnzasAGramosAsync(double onzas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ToneladasAKg", ReplyAction="http://tempuri.org/IService1/ToneladasAKgResponse")]
        double ToneladasAKg(double toneladas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ToneladasAKg", ReplyAction="http://tempuri.org/IService1/ToneladasAKgResponse")]
        System.Threading.Tasks.Task<double> ToneladasAKgAsync(double toneladas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CLIESC_ConUni_DotNet_GR6.MiServicio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CLIESC_ConUni_DotNet_GR6.MiServicio.IService1>, CLIESC_ConUni_DotNet_GR6.MiServicio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CelsiusAFahrenheit(double celsius) {
            return base.Channel.CelsiusAFahrenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusAFahrenheitAsync(double celsius) {
            return base.Channel.CelsiusAFahrenheitAsync(celsius);
        }
        
        public double FahrenheitACelsius(double fahrenheit) {
            return base.Channel.FahrenheitACelsius(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitACelsiusAsync(double fahrenheit) {
            return base.Channel.FahrenheitACelsiusAsync(fahrenheit);
        }
        
        public double CelsiusAKelvin(double celsius) {
            return base.Channel.CelsiusAKelvin(celsius);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusAKelvinAsync(double celsius) {
            return base.Channel.CelsiusAKelvinAsync(celsius);
        }
        
        public double KelvinACelsius(double kelvin) {
            return base.Channel.KelvinACelsius(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> KelvinACelsiusAsync(double kelvin) {
            return base.Channel.KelvinACelsiusAsync(kelvin);
        }
        
        public double FahrenheitAKelvin(double fahrenheit) {
            return base.Channel.FahrenheitAKelvin(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitAKelvinAsync(double fahrenheit) {
            return base.Channel.FahrenheitAKelvinAsync(fahrenheit);
        }
        
        public double KelvinAFahrenheit(double kelvin) {
            return base.Channel.KelvinAFahrenheit(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> KelvinAFahrenheitAsync(double kelvin) {
            return base.Channel.KelvinAFahrenheitAsync(kelvin);
        }
        
        public double KmAMetros(double kilometros) {
            return base.Channel.KmAMetros(kilometros);
        }
        
        public System.Threading.Tasks.Task<double> KmAMetrosAsync(double kilometros) {
            return base.Channel.KmAMetrosAsync(kilometros);
        }
        
        public double MetrosACm(double metros) {
            return base.Channel.MetrosACm(metros);
        }
        
        public System.Threading.Tasks.Task<double> MetrosACmAsync(double metros) {
            return base.Channel.MetrosACmAsync(metros);
        }
        
        public double PulgadasACm(double pulgadas) {
            return base.Channel.PulgadasACm(pulgadas);
        }
        
        public System.Threading.Tasks.Task<double> PulgadasACmAsync(double pulgadas) {
            return base.Channel.PulgadasACmAsync(pulgadas);
        }
        
        public double PiesAMetros(double pies) {
            return base.Channel.PiesAMetros(pies);
        }
        
        public System.Threading.Tasks.Task<double> PiesAMetrosAsync(double pies) {
            return base.Channel.PiesAMetrosAsync(pies);
        }
        
        public double MillasAKm(double millas) {
            return base.Channel.MillasAKm(millas);
        }
        
        public System.Threading.Tasks.Task<double> MillasAKmAsync(double millas) {
            return base.Channel.MillasAKmAsync(millas);
        }
        
        public double KgAGramos(double kilogramos) {
            return base.Channel.KgAGramos(kilogramos);
        }
        
        public System.Threading.Tasks.Task<double> KgAGramosAsync(double kilogramos) {
            return base.Channel.KgAGramosAsync(kilogramos);
        }
        
        public double GramosAMg(double gramos) {
            return base.Channel.GramosAMg(gramos);
        }
        
        public System.Threading.Tasks.Task<double> GramosAMgAsync(double gramos) {
            return base.Channel.GramosAMgAsync(gramos);
        }
        
        public double LibrasAKg(double libras) {
            return base.Channel.LibrasAKg(libras);
        }
        
        public System.Threading.Tasks.Task<double> LibrasAKgAsync(double libras) {
            return base.Channel.LibrasAKgAsync(libras);
        }
        
        public double OnzasAGramos(double onzas) {
            return base.Channel.OnzasAGramos(onzas);
        }
        
        public System.Threading.Tasks.Task<double> OnzasAGramosAsync(double onzas) {
            return base.Channel.OnzasAGramosAsync(onzas);
        }
        
        public double ToneladasAKg(double toneladas) {
            return base.Channel.ToneladasAKg(toneladas);
        }
        
        public System.Threading.Tasks.Task<double> ToneladasAKgAsync(double toneladas) {
            return base.Channel.ToneladasAKgAsync(toneladas);
        }
    }
}
