//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiServicio
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiServicio.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IService1/CelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelsiusAFahrenheitAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitACelsius", ReplyAction="http://tempuri.org/IService1/FahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitACelsiusAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusAKelvin", ReplyAction="http://tempuri.org/IService1/CelsiusAKelvinResponse")]
        System.Threading.Tasks.Task<double> CelsiusAKelvinAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KelvinACelsius", ReplyAction="http://tempuri.org/IService1/KelvinACelsiusResponse")]
        System.Threading.Tasks.Task<double> KelvinACelsiusAsync(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitAKelvin", ReplyAction="http://tempuri.org/IService1/FahrenheitAKelvinResponse")]
        System.Threading.Tasks.Task<double> FahrenheitAKelvinAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KelvinAFahrenheit", ReplyAction="http://tempuri.org/IService1/KelvinAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> KelvinAFahrenheitAsync(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KmAMetros", ReplyAction="http://tempuri.org/IService1/KmAMetrosResponse")]
        System.Threading.Tasks.Task<double> KmAMetrosAsync(double kilometros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MetrosACm", ReplyAction="http://tempuri.org/IService1/MetrosACmResponse")]
        System.Threading.Tasks.Task<double> MetrosACmAsync(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PulgadasACm", ReplyAction="http://tempuri.org/IService1/PulgadasACmResponse")]
        System.Threading.Tasks.Task<double> PulgadasACmAsync(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PiesAMetros", ReplyAction="http://tempuri.org/IService1/PiesAMetrosResponse")]
        System.Threading.Tasks.Task<double> PiesAMetrosAsync(double pies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MillasAKm", ReplyAction="http://tempuri.org/IService1/MillasAKmResponse")]
        System.Threading.Tasks.Task<double> MillasAKmAsync(double millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KgAGramos", ReplyAction="http://tempuri.org/IService1/KgAGramosResponse")]
        System.Threading.Tasks.Task<double> KgAGramosAsync(double kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GramosAMg", ReplyAction="http://tempuri.org/IService1/GramosAMgResponse")]
        System.Threading.Tasks.Task<double> GramosAMgAsync(double gramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LibrasAKg", ReplyAction="http://tempuri.org/IService1/LibrasAKgResponse")]
        System.Threading.Tasks.Task<double> LibrasAKgAsync(double libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OnzasAGramos", ReplyAction="http://tempuri.org/IService1/OnzasAGramosResponse")]
        System.Threading.Tasks.Task<double> OnzasAGramosAsync(double onzas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ToneladasAKg", ReplyAction="http://tempuri.org/IService1/ToneladasAKgResponse")]
        System.Threading.Tasks.Task<double> ToneladasAKgAsync(double toneladas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IService1Channel : MiServicio.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MiServicio.IService1>, MiServicio.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<double> CelsiusAFahrenheitAsync(double celsius)
        {
            return base.Channel.CelsiusAFahrenheitAsync(celsius);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitACelsiusAsync(double fahrenheit)
        {
            return base.Channel.FahrenheitACelsiusAsync(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusAKelvinAsync(double celsius)
        {
            return base.Channel.CelsiusAKelvinAsync(celsius);
        }
        
        public System.Threading.Tasks.Task<double> KelvinACelsiusAsync(double kelvin)
        {
            return base.Channel.KelvinACelsiusAsync(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitAKelvinAsync(double fahrenheit)
        {
            return base.Channel.FahrenheitAKelvinAsync(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> KelvinAFahrenheitAsync(double kelvin)
        {
            return base.Channel.KelvinAFahrenheitAsync(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> KmAMetrosAsync(double kilometros)
        {
            return base.Channel.KmAMetrosAsync(kilometros);
        }
        
        public System.Threading.Tasks.Task<double> MetrosACmAsync(double metros)
        {
            return base.Channel.MetrosACmAsync(metros);
        }
        
        public System.Threading.Tasks.Task<double> PulgadasACmAsync(double pulgadas)
        {
            return base.Channel.PulgadasACmAsync(pulgadas);
        }
        
        public System.Threading.Tasks.Task<double> PiesAMetrosAsync(double pies)
        {
            return base.Channel.PiesAMetrosAsync(pies);
        }
        
        public System.Threading.Tasks.Task<double> MillasAKmAsync(double millas)
        {
            return base.Channel.MillasAKmAsync(millas);
        }
        
        public System.Threading.Tasks.Task<double> KgAGramosAsync(double kilogramos)
        {
            return base.Channel.KgAGramosAsync(kilogramos);
        }
        
        public System.Threading.Tasks.Task<double> GramosAMgAsync(double gramos)
        {
            return base.Channel.GramosAMgAsync(gramos);
        }
        
        public System.Threading.Tasks.Task<double> LibrasAKgAsync(double libras)
        {
            return base.Channel.LibrasAKgAsync(libras);
        }
        
        public System.Threading.Tasks.Task<double> OnzasAGramosAsync(double onzas)
        {
            return base.Channel.OnzasAGramosAsync(onzas);
        }
        
        public System.Threading.Tasks.Task<double> ToneladasAKgAsync(double toneladas)
        {
            return base.Channel.ToneladasAKgAsync(toneladas);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.12:8080/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
